### PR TITLE
Drop baseline compiler

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by dinfuehr** [comment]
Dropping baseline was meant as a last resort, we didn't even try to update baseline as well. Let's keep it for now.

**Comment by dinfuehr** [comment]
Thank you very much 👍

**Comment by soc** [comment]
No problem! Did you find the differences between baseline and cannon you wanted to sort out?

**Comment by dinfuehr** [comment]
Not in too much detail TBH. But I think with our limited time it is not worth to keep the second compiler around for much longer

**Pull request merged**
