### PR TITLE
Allow constructor varargs and use them

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by dinfuehr** [comment]
My first reaction after looking at the failed tests was that it's probably safer for now to not break already existing tests (even with the old baseline compiler). If this is too much work, we could consider dropping baseline entirely though. Agreed, implementing the array constructor as an intrinsic should simplify the code and make it easier to change in the future.

**Comment by soc** [comment]
Will do!

**Comment by soc** [comment]
@dinfuehr Dropping baseline is https://github.com/dinfuehr/dora/pull/223.

I also removed the third commit with the array stuff, so that this PR with the first two commits should be fine know.

**Comment by soc** [comment]
@dinfuehr Rebased, could you have a look?

**Comment by dinfuehr** [comment]
Thanks, looks good! Could you please test the case where the varargs argument isn't the last argument in a constructor. There is one for regular functions already.

**Comment by soc** [comment]
Will do!

**Pull request merged**
