### PR TITLE
Added Defer Token

### PR DESCRIPTION
**Pull request by riginding**

### CODE REVIEW

**Comment by riginding** [comment]
I've seen the 'finally' keyword in token.rs

whats the order of execution if there's finally and defer in the same function?

**Comment by dinfuehr** [comment]
Thanks, great!

**Comment by dinfuehr** [comment]
I would translate `defer` like this:

```
{
  <before>
  defer foo();
  <after>
}
```

should become this block:

```
{
  <before>;
  do {
    <after>
  } finally {
    foo();
  }
}
```

`finally` in `<before>`, `<after>` or sorrounding block shouldn't be important. Did you mean something else?

**Comment by riginding** [comment]
what about?

``` dora
{
  <before>
  defer foo1();
  defer foo2();
  <after>
}
```
should this be:
``` dora
{
  <before>
  do {
    <after>
  } finally {
    foo2();
    foo1();
  }
}
```

**Comment by riginding** [comment]
what about this? is this valid?

```
{
  do {
    <before1>
    defer foo();
    <after1>
  } finally {
    <before2>
    defer foo2();
    <after2>
  }
}
```

**Comment by dinfuehr** [comment]
I wouldn't really try to optimize this in the baseline compiler, just generate nested blocks:

``` dora
{
  <before>
  do {
    do {
      <after>
    } finally {
      foo2();
    }
  } finally {
    foo1();
  }
}
```

The second example should also be valid and generated as this:

```
{
  do {
    <before1>
    do {
      <after1>
    } finally {
      foo();
    }
  } finally {
    <before2>
    do {
      <after2>
    } finally {
      foo2();
    }
  }
}
```

`defer` is just syntactic sugar for the first pattern. I think we can use these examples as tests...

**Pull request merged**
