### PR TITLE
Implement Sortable for Float and Double

### LINKED ISSUE #115: Implement Sortable for Float/Double

### PR DESCRIPTION
**Pull request by soc**
Fixes #115.

### CODE REVIEW

**Comment by soc** [comment]
`assert((-0.0F).sortsAs(-0.0F) == 0);` vs. `assert(-0.0F.sortsAs(-0.0F) == 0); //fail`.

That took a while to figure out. :-)

**Comment by dinfuehr** [comment]
Looks good to me, before merging: Does it make sense to add tests for NaN as well?

**Comment by dinfuehr** [comment]
(e.g. comparing NaN to non-NaN values)

**Comment by soc** [comment]
Yes, absolutely, I'll add more tests. Thanks!

**Comment by soc** [comment]
@dinfuehr More tests added in https://github.com/dinfuehr/dora/pull/119/commits/734c6746125f5b01249445670354d5d627fd2ed8.

**Comment by dinfuehr** [comment]
Thanks!

**Pull request merged**
