### PR TITLE
Implement more methods on Array and Vec

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by dinfuehr** [comment]
Very cool and useful! Something we could discuss at a later point: Maybe those `toString` methods on Array and Vec could use a different name e.g. `inspect` or so like Ruby calls it. I would assume their output is extremely useful for developers but users probably don't really know what `Array` or `Vec` is.

**Comment by soc** [comment]
Agreed! I had plans to write up a proposal regarding the distinction of `String` for debugging and `String` for user-facing information; I'll try speeding that up so we can discuss this.

**Comment by soc** [comment]
@dinfuehr Perhaps it makes sense to activate the GitHub discussions feature, such that we don't clog up the issues tab with discussion topics?

**Comment by dinfuehr** [comment]
I can activate it, I am just a bit worried that we get too many communication channels...

**Comment by soc** [comment]
I'd say let's try it, we can always close it down again if it doesn't feel beneficial.

**Pull request merged**
